#!/bin/bash

zmodule environment
zmodule input
zmodule termtitle

# completions
if type brew &>/dev/null
then
    zmodule $(brew --prefix)/share/zsh -n homewbrew --fpath site-functions
fi

if type "gh" > /dev/null; then
    zmodule zdharma-continuum/null \
        -n gh-completion \
        --on-pull "gh completion -s zsh > _comp" \
        -s "_comp"
fi

zmodule zsh-users/zsh-autosuggestions
zmodule completion
zmodule utility

zmodule zsh-users/zsh-history-substring-search
zmodule zsh-users/zsh-syntax-highlighting

zmodule romkatv/powerlevel10k

